version: '3'
services:
  elasticsearch:
    image: "elasticsearch:5"
    networks:
      - frontend
    restart: always
    volumes:
      - ./ES_DATA:/usr/share/elasticsearch/data


  hacker:
    image: "dineshsonachalam/hacker:1.0.0"
    networks:
      - frontend
    restart: always
    ports:
      - "8005:8005"


networks:
  frontend:
